// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fgtotjhboxecmszsnfua.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZndG90amhib3hlY21zenNuZnVhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk3NDMwNDksImV4cCI6MjA3NTMxOTA0OX0.tvlrY-wUjmvW5nICQXfLmpVrlz9QkqHbTAyE7j36FpM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});